name: 'Yarn and NextJS cache'
description: 'Get stored cache for yarn and NextJS'
inputs:
  GIT_TOKEN: #maybe not needed?
    description: 'GIT_TOKEN from secrets'
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo step
      uses: ./composite-actions/.github/workflows/actions/echo-step
      with:
        PRINT: "Get yarn cache directory path"

    # https://github.com/actions/cache/blob/master/examples.md#node---yarn
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: |
        yarn_version=$(yarn -v)
        first_letter_of_version=${yarn_version:0:1}
        number=$((first_letter_of_version))
        if (( "$number" < 2 )); then
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        else
          echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        fi
      env:
        GIT_TOKEN: ${{ inputs.GIT_TOKEN }}

    - name: Echo step
      uses: ./composite-actions/.github/workflows/actions/echo-step
      with:
        PRINT: "Restore Yarn cache"

    - name: Echo step
      uses: ./composite-actions/.github/workflows/actions/echo-step
      with:
        PRINT: "Yarn install"

    - name: Yarn install
      shell: bash
      run: yarn install
      env:
        GIT_TOKEN: ${{ inputs.GIT_TOKEN }}

    - name: Echo step
      uses: ./composite-actions/.github/workflows/actions/echo-step
      with:
        PRINT: "NextJS cache"

    # https://github.com/zeit/next.js/blob/master/errors/no-cache.md
    - name: NextJS cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
