name: 'Error step'
description: 'Print error message in red'
inputs:
  PRINT:
    description: 'This will be printed'
    required: true

runs:
  using: "composite"
  steps:
  - name: Print
    shell: bash
    run: |
        RED="\033[0;31m"
        printf "\n${RED}${{ inputs.PRINT }}\n"
        echo ${{ inputs.PRINT }} >> $GITHUB_STEP_SUMMARY
