name: 'Sonarcloud react'
description: 'React steps for sonarcloud'
inputs:
  GIT_TOKEN: 
    description: 'GIT_TOKEN from secrets'
    required: true
  NODE_VERSION: 
    description: 'Node version'
    required: true
  SONAR_TOKEN: 
    description: 'SONAR_TOKEN from secrets'
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup node
    uses: ./composite-actions/.github/workflows/actions/react/setup-node
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}

  - name: Get yarn and NextJS cache
    uses: ./composite-actions/.github/workflows/actions/react/yarn-cache
    with:
      GIT_TOKEN: ${{ inputs.GIT_TOKEN }}
      
  - name: Install yarn
    uses: ./composite-actions/.github/workflows/actions/react/yarn-install
    with:
      GIT_TOKEN: ${{ inputs.GIT_TOKEN }}
  
  - name: Echo step
    uses: ./composite-actions/.github/workflows/actions/echo-step
    with:
      PRINT: "SonarCloud Scan"

  - name: SonarCloud Scan
    uses: sonarsource/sonarcloud-github-action@v1.6
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
