name: 'Publish package'
description: 'Publish package and set version'
inputs:
  GIT_TOKEN:
    description: 'GIT_TOKEN from secrets'
    required: true
  MAIL:
    description: 'MAIL from secrets'
    required: true

runs:
  using: "composite"
  steps:
  - name: Echo step
    uses: ./composite-actions/.github/workflows/actions/echo-step
    with:
      PRINT: "Publish package and set version"

  - name: Config git
    shell: bash
    run: |
      git config --global user.name 'Github Actions'
      git config --global user.email ''${{ inputs.MAIL }}''

  - run: yarn config set version-git-tag true
    shell: bash

  - run: yarn config set version-tag-prefix "v"
    shell: bash

  - run: yarn config set version-git-message "Update to version v%s [skip actions]"
    shell: bash

  - run: yarn version --patch
    shell: bash

  - run: yarn publish
    shell: bash
    env:
      NPM_AUTH_TOKEN: ${{ inputs.GIT_TOKEN }}

  - name: Git push version update
    shell: bash
    run: git push
