name: 'Install yarn'
description: 'Install yarn with --immutable cache'
inputs:
  GIT_TOKEN:
    description: 'GIT_TOKEN from secrets'
    required: true
  
runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: bash
    run: |
      yarn install --immutable-cache
