on:
  workflow_call:

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Label when approved
        uses: TobKed/label-when-approved-action@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'approved'
