on:
  workflow_call:

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
