on:
  workflow_call:
    inputs:
      FRAMEWORK:
        required: true
        type: string
      NODE_VERSION:
        required: false
        default: "18.2.0"
        type: string

name: Main Workflow

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, '$DEPLOYED/${{ github.event.repository.name }}')"
    env: 
      DEPLOYED: ${{ secrets.DEPLOYED }}

    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}

      - name: Checkout composite actions
        uses: actions/checkout@v3.0.2
        with:
          repository: afa-forsakring-fou/github-actions
          path: composite-actions      

      - name: React steps
        if: "${{ inputs.FRAMEWORK == 'react' }}"
        uses: ./composite-actions/.github/workflows/actions/react
        with:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          X_HASURA_ADMIN_SECRET: ${{ secrets.X_HASURA_ADMIN_SECRET }}
          HASURA_URL: ${{ secrets.HASURA_URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Dotnet steps
        if: "${{ inputs.FRAMEWORK == 'dotnet' }}"
        uses: ./composite-actions/.github/workflows/actions/dotnet
        with:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, '$DEPLOYED/${{ github.event.repository.name }}')"
    env: 
      DEPLOYED: ${{ secrets.DEPLOYED }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}

      - name: Checkout composite actions
        uses: actions/checkout@v3.0.2
        with:
          repository: afa-forsakring-fou/github-actions
          path: composite-actions

      - name: React sonarcloud
        if: "${{ inputs.FRAMEWORK == 'react' }}"
        uses: ./composite-actions/.github/workflows/actions/react/sonarcloud
        with:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Dotnet sonarcloud
        if: "${{ inputs.FRAMEWORK == 'dotnet' }}"
        uses: ./composite-actions/.github/workflows/actions/dotnet/sonarcloud
        with:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-to-gke:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}

      - name: Config git
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email ''${{ secrets.MAIL }}''

      # fou-web has three cache steps here 

      - id: auth
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          version: 350.0.0

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Set up GKE + Docker
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Set up kustomize (will kustomize change from /master/ to /main/ soon?)
      - name: Set up Kustomize
        run: |-
          cd /usr/bin
          curl -s "https://raw.githubusercontent.com/\
          kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | sudo bash

      # Build the Docker image, Publish it to the image repository, Commit the new tag reference, Push those commits
      - name: Build
        run: |
          make env deploy_ci
        env:
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          GIT_USER: "GithubActions"
          X_HASURA_ADMIN_SECRET: ${{ secrets.X_HASURA_ADMIN_SECRET }}
