name: 'Submodule check'
description: 'If repo has our submodule then check for the skip annotation'

runs:
  using: "composite"
  steps:
  - name: Check if submodule and check for 'database_update:'
    id: check-submodule
    shell: bash
    run: |
      if [[ ! $(git submodule status) ]]; then
        exit 0
      else
        cd shared-tools/makefiles
        if ! [[ $(cat ef_migrations.mk | grep "database_update:") ]]; then
          exit 1
        fi
      fi

  - name: Print error message
    if: failure() && steps.check-submodule.outcome != 'success'
    uses: ./composite-actions/.github/workflows/actions/error-step
    with:
      PRINT: "Pull latest submodule!"
